tushare:
  token: ''

quote:
  fields:
    open:
      precision: 1000
    high:
      precision: 1000
    low:
      precision: 1000
    close:
      precision: 1000
    volume:
      precision: 1

analysis:
  round: 6
  remove_cent:
    cn_volume: 1000
    cn_price: 1
    us_volume: 30000
    us_price: 3

  current_position:                 # 当前bar所在位置
    reverse_ratio: 0.2              # 翻转涨跌幅
    platform_volatility: 0.01       # 平台波动限制
    break_ratio: 0.1                # 平台突破最小波动

classical:
  three_red_soldiers:
    close_growth_max_limit: 0.05    # 每日增长最大限制
    close_growth_min_limit: 0.01    # 每日增长最小限制
    open_pct_min_limit: 0.5         # 开盘价在昨日实体百分比位置
    high_pct_max_limit: 0.012       # 上影线最大比例限制

  three_crow:
    open_pos_pct: 0.5
    low_pct: 0.012                  # 下影线比例

  multi_cannon:
    growth_pct_min: 0.03

  morning_star:
    body_change_pct_3: 0.05   # 倒数第三天下跌百分比
    body_change_pct_2: 0.03   # 倒数第二天star 涨跌不超过
    body_change_pct_1: 0.05   # 倒数第一天上涨百分比

  duck_head:
    min_period: 8
    min_fall_count: 6
    mid_period: 18
    mid_growth_count: 15
    max_period: 55
    low_ma_ratio: 0.03

  golden_cross:
    min_period: 5
    mid_period: 10
    max_period: 20

  dead_cross:
    min_period: 5
    mid_period: 10
    max_period: 20

  find_corner:
    ext_depth: 12
    ext_deviation: 0.1
    ext_backstep: 3

  w_form:
    volatility: 0.05
    count_limit: 1

  m_form:
    volatility: 0.05
    count_limit: 1

similar_k_bar:
  skyrocket:
    similar_day_num: 30
    backtrack_day_num: 60
    filter_symbol_num: 30
    rise_day_num: 4
    recommend_num: 5
  prediction:
    similar_symbol_num: 30
    recommend_num: 3
    bulk_size: 200
    prediction_symbol_num: 5